FROM apache/airflow:2.2.5-python3.8
ENV SYNQ_VERSION=v1.2.3
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget && \
    apt-get clean && \
    rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*
RUN wget -O /usr/bin/synq-dbt https://github.com/getsynq/synq-dbt/releases/download/${SYNQ_VERSION}/synq-dbt-amd64-linux && \
    chmod +x /usr/bin/synq-dbt
