#Docs https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml

dags:
  gitSync:
    # Docs https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L1305
    enabled: true
    repo: https://github.com/getsynq/synq-dbt-airflow.git
    branch: main
    subPath: ""
    # must be the same as airflow user
    image:
      uid: 50000
      gid: 50000

airflow:

  image:
      repository: ghcr.io/getsynq/airflow-synq-dbt
      tag: "1.0.0"

  extraPipPackages:
    - "airflow-dbt==0.4.0"
    - "dbt-postgres==1.2.0" # If dbt-core 1.3.0 is used there is a jinja2 conflict with airflow itself
  extraEnv:
    - name: "SYNQ_TOKEN"
      value: "placeholder"
