dags:
  gitSync:
    enabled: true
    repo: https://github.com/getsynq/synq-dbt-airflow.git
    branch: main
    subPath: ""

airflow:
  extraPipPackages:
    - "airflow-dbt==0.4.0"
    - "dbt-postgres==1.2.0" # If dbt-core 1.3.0 is used there is a jinja2 conflict with airflow itself

#   install-pip-packages ERROR: Cannot install apache-airflow==2.2.5 and dbt-postgres because these package versions have conflicting dependencies.                                          │
# │ install-pip-packages                                                                                                                                                                     │
# │ install-pip-packages The conflict is caused by:                                                                                                                                          │
# │ install-pip-packages     dbt-core 1.3.0 depends on Jinja2==3.1.2                                                                                                                         │
# │ install-pip-packages     apache-airflow 2.2.5 depends on jinja2<3.1 and >=2.10.1                                                                                                         │
# │ install-pip-packages                                                                                                                                                                     │
# │ install-pip-packages To fix this you could try to:                                                                                                                                       │
# │ install-pip-packages 1. loosen the range of package versions you've specified                                                                                                            │
# │ install-pip-packages 2. remove package versions to allow pip attempt to solve the dependency conflict                                                                                    │
# │ install-pip-packages                                                                                                                                                                     │
# │ install-pip-packages ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
