# example profiles.yml file
dbt_example:
  target: dev
  outputs:
    dev:
      type: postgres
      host: airflow-postgresql.airflow-dbt.svc.cluster.local
      user: postgres
      password: airflow
      port: 5432
      dbname: airflow
      # dbname: localhost
      schema: dbt_example
      threads: 4
